[actions]
baseline_tests = true
scaling_tests = true

[logger]
# Basic output no timestamp, no filename
# Set level to 'INFO' to output terminal, root pairs and solutions
level = "SUCCESS"
format = "<level>{message}</level>"

# The loguru default format string (useful when debugging).
# level = "DEBUG"
# format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

# HiGHS MIP solver options.
[solver]
log_to_console = false
mip_heuristic_run_root_reduced_cost = false
mip_feasibility_tolerance = 1e-5
mip_improvement_timeout = inf
threads = 8                                 # HiGHs internal parallelism
num_threads = 1                             # concurrent HiGHs threads
time_limit = inf
