[actions]
baseline_tests = false
scaling_tests = true

[logger]
# Basic output no timestamp, no filename
# Set level to 'INFO' to output terminal, root pairs and solutions
# DEBUG and TRACE can be used for PD Aprroximation and the DO_DBG
# cariable can be set in the rust files for debugging output.
level = "SUCCESS"
format = "<level>{message}</level>"

# The loguru default format string.
# level = "DEBUG"
# format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[exploration_data]
directed = true
edge_weighted = false   # Exists for future terminal cluster solving.
omit_great_ocean = true

# Solver is not used by the approximation functions but needs
# to be present for the current scaling tests setup and will be
# used in the future for solving the terminal clusters after
# the approximation.
[solver]
log_to_console = false
mip_heuristic_run_root_reduced_cost = false
mip_improvement_timeout = inf
mip_feasibility_tolerance = 1e-4
mip_rel_gap = 1e-4
primal_feasibility_tolerance = 1e-4
threads = 8                                 # HiGHs internal parallelism
num_threads = 1                             # concurrent HiGHs threads
time_limit = inf

# [solution]
# cleanup = true
# validate = true
